### ISSUE TITLE
refactor to use Microsoft.Maui.Graphics 

### ISSUE THREAD

**Issue by lytico** [dotnet/GraphicsControls#19]
maybe the whole project could be refactored based on

https://github.com/dotnet/Microsoft.Maui.Graphics

so that all platform specific code comes from there

remark:
MAUI is now based on Microsoft.Maui.Graphics, see: https://github.com/dotnet/maui/commit/b1866fd187b7e94c449e5617ff315b8dfe5576ed

**Comment by jsuarezruiz** [comment]
The project is based on System.Graphics that now, is Microsoft.Maui.Graphics and yes, the project will be updated to use Microsoft.Maui.Graphics and also use the Handlers architecture.

**Comment by lytico** [comment]
thanks for explanation! i wasn't aware that System.Graphics == Microsoft.Maui.Graphics
i just looked into the code, and have overseen that it's mentioned in https://github.com/dotnet/GraphicsControls#readme
