### ISSUE TITLE
Feedback for some additional view

### ISSUE THREAD

**Issue by sattasundar** [dotnet/GraphicsControls#4]
I think you guys are doing awesome works. 

But I have some observation regarding Entry/Editor/Picker as Outlined control. 

e.g.
![](https://help.syncfusion.com/xamarin/text-input-layout/Container-Type-images/textInput_container_img2.png)
 
Basically we can say InputLayout.

If we make this Outline as Property for supported control.

**Comment by jsuarezruiz** [comment]
The initial idea is to have all the controls available in Visual Xamarin.Forms, with the same possibilities (properties, events etc):

- ActivityIndicator
- Button
- Check box
- DatePicker
- Editor
- Entry
- Frame
- Picker
- ProgressBar
- Slider
- Stepper
- TimePicker

This would be to have a Core of drawn controls with high performance, customization possibilities and with support for accessibility, RTL, etc.  Later, yes, we can include more possibilities like:

`<Button MaterialStyle="Outline"></Button>`

**Comment by sattasundar** [comment]
yeah, great idea. -:)

**Comment by jsuarezruiz** [comment]
@sattasundar I saved the idea for the future, for now being focused on implementing the Core of the controls without extra properties or functionality, I am going to close the issue. Thanks for the feedback!
